package org.example.stockwatch247.model.enums;

public enum CandlePattern {
    ANY,
    BULLISH_ENGULFING,
    BEARISH_ENGULFING,
    DOJI,
    HAMMER,
    INVERTED_HAMMER,
    HANGING_MAN,
    SHOOTING_STAR,
    MORNING_STAR,
    EVENING_STAR,
    PIERCING_LINE,
    DARK_CLOUD_COVER,
    BULLISH_HARAMI,
    BEARISH_HARAMI,
    THREE_WHITE_SOLDIERS,
    THREE_BLACK_CROWS,
    ELLIOTT_BULLISH_IMPULSE,
    ELLIOTT_BEARISH_IMPULSE,
    ELLIOTT_BULLISH_WAVE_V_END,
    ELLIOTT_BEARISH_WAVE_V_END,
    ELLIOTT_BULLISH_CORRECTION,
    ELLIOTT_BEARISH_CORRECTION
}
