alter table candles
    add column if not exists updated_at timestamptz not null default current_timestamp;

create index if not exists idx_candles_signal_cache_revision
    on candles (symbol, time_interval, updated_at desc);

create table if not exists historical_signal_cache (
    id bigint generated by default as identity primary key,
    symbol varchar(64) not null,
    time_interval varchar(16) not null,
    signal_family varchar(32) not null,
    detector_version varchar(64) not null,
    settings_hash varchar(64) not null,
    candle_count bigint not null,
    latest_candle_timestamp bigint,
    candle_revision timestamptz,
    payload jsonb not null,
    calculated_at timestamptz not null default current_timestamp,
    last_accessed_at timestamptz not null default current_timestamp,
    constraint uk_historical_signal_cache_profile unique
        (symbol, time_interval, signal_family, detector_version, settings_hash)
);

create index if not exists idx_historical_signal_cache_lookup
    on historical_signal_cache
        (symbol, time_interval, signal_family, detector_version, settings_hash);

create index if not exists idx_historical_signal_cache_cleanup
    on historical_signal_cache (last_accessed_at);

